#!/usr/bin/env bash
# Installs nginx web server

# apt-get update
# apt-get install -y nginx
sed -i '/^}/i \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default
service nginx restart
