#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

if [! -d "/backup"]; then
  mkdir /backup
fi

mysqldum -uroot -p"$1" --all-databases > /backup/backup.sql
tar -czvf /backup/date +%d-%m-%Y.tar.gz /backup/backup.sql
rm /backup/backup.sql
