#!/usr/bin/env bash
#configure nginx to run on port 80

sudo chmod u+w /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
