#!/usr/bin/env bash
# Open the 80 port
sudo systemctl start nginx
sudo sed -i 's/liste\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo nginx -t
sudo systemctl restart nginx
