#!/usr/bin/env bash
#Bash script that configures nginx to run as nginx user and must be listening from port 8080

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user=www-data;/user=nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\*80/listen8080/' /etc/nginx/sites-available/default
sudo service nginx restart
